parameters:
    app.map_dir: 'map.yaml'

services:
    SymfonyApiMapper\SymfonyApiMapper:
        autowire: true
        arguments:
            $mapDir: '%app.map_dir%'

    app.mapper:
        alias: SymfonyApiMapper\SymfonyApiMapper
        public: true 